### ISSUE TITLE
Test coverage under Node 4.x?

### ISSUE THREAD

**Issue by vielmetti** [bigeasy/proof#290]
I made a branch in my fork and tested NodeJS 4.x and all of the tests passed. I don't know where node 4  testing fits into your plans, but if it does fit into your plans, happy to submit a PR.

**Comment by bigeasy** [comment]
Sure. What would the PR include?

**Comment by vielmetti** [comment]
Two lines of configuration to .travis.yml and that's it. https://github.com/vielmetti/proof/pull/1

**Comment by bigeasy** [comment]
Excellent. :+1:

**Comment by bigeasy** [comment]
Include "Closes #290".
